# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'IOSProjectInit' do
pod 'ReactiveCocoa', '~> 2.5'
pod 'Masonry'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MJExtension'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage/WebP'
end

